### PR TITLE
update Indent rule

### PR DESCRIPTION
**Pull request by pat-s**
Referring to https://github.com/cereda/arara/issues/87

I do not know if that covers everything Chris has changed since I could not find a full changelog but its a start. 
Nothing special as I have no experience with perl and only minor in YAML 😄 
Let's see if the build passes.

### CODE REVIEW

**Comment by cereda** [comment]
Looks fine to me. 😉

**Comment by cmhughes** [comment]
Thanks for looking at this. Regarding line 26, should it be:
```
 +  flag: "@{isTrue(parameters.modifylinebreaks, '-m')}" 
```
Also, can the `-o` switch be updated to reflect the changes in https://github.com/cereda/arara/issues/87

**Comment by pat-s** [comment]
@cmhughes 
I'll fix it right away. Regarding the `-o` changes: Would this be okay?

```
- identifier: outputfile
  flag: "@{[ '-o', output.tex ]}"
```

**Comment by cereda** [comment]
I don't remember how the underlying execution library handles `-p=v` key/value arguments, I will take a look later on and report back.

**Pull request merged**
